name: CI

on:
    push:
        branches: [master]
    pull_request:

jobs:
    ci:
        uses: apermo/reusable-workflows/.github/workflows/reusable-ci.yml@main
        with:
            php-versions: '["8.2", "8.3", "8.4"]'
            codecov-upload: true
        secrets:
            codecov-token: ${{ secrets.CODECOV_TOKEN }}
